export const site = {
  name: 'Melhor Lava e Seca',
  tagline: 'Reviews honestos das melhores lava e seca do Brasil',
  url: 'https://melhorlavaeseca.com',
  domain: 'melhorlavaeseca.com',
  locale: 'pt-BR',
  country: 'BR',
  author: 'Equipe Melhor Lava e Seca',
  email: 'contato@melhorlavaeseca.com',
  founded: '2024',
  amazonPartnerTag: 'melhorlavaeseca-20',
  social: {
    instagram: 'https://instagram.com/melhorlavaeseca',
    youtube: 'https://youtube.com/@melhorlavaeseca',
  },
  nav: [
    { label: 'Melhor Lava e Seca', href: '/' },
    { label: 'Ranking', href: '/#ranking' },
    { label: 'Guia de compra', href: '/#guia' },
    { label: 'Comparativo', href: '/#comparativo' },
    { label: 'FAQ', href: '/#faq' },
    { label: 'Blog', href: '/blog/' },
  ],
  footerNav: [
    { label: 'Sobre', href: '/sobre/' },
    { label: 'Contato', href: '/contato/' },
    { label: 'Política de privacidade', href: '/privacidade/' },
    { label: 'Termos de uso', href: '/termos/' },
    { label: 'Política de afiliados', href: '/afiliados/' },
  ],
};
