import Link from 'next/link';
import InstitutionalPage from '@/components/InstitutionalPage';
import { buildMetadata } from '@/lib/seo';
export const metadata=buildMetadata({title:"Sobre o Melhor Lava e Seca",description:"Entenda como comparamos lava e seca, quais fontes consultamos, quem assina os artigos e como os links de afiliado ajudam a manter o site.",path:'/sobre/'});
export default function Page(){return <InstitutionalPage title="Sobre o Melhor Lava e Seca" path="/sobre/"><p>O Melhor Lava e Seca reúne comparativos e orientações para ajudar na escolha e no uso de lavadoras com secagem. O conteúdo é editorial; o site não vende os equipamentos.</p>
<h2>Como comparamos os modelos</h2><p>A seleção principal é uma análise documental de fichas e páginas de fabricantes. Comparamos capacidades de lavagem e secagem separadamente, recursos declarados e pontos que precisam ser conferidos antes da compra.</p><p>Os links das fontes estão nos cartões de cada modelo. Dados sem confirmação aparecem como “Consultar ficha”. Sufixos, tensão e ano de fabricação podem alterar características: confira o código completo no anúncio e no manual.</p><p>Os números da seleção servem para localizar cada item. Não representam notas de laboratório ou uma medição de desempenho. Não apresentamos experiências de uso pessoal como prova de teste.</p>
<h2>Fontes e atualização</h2><p>Uma página de suporte ajuda a localizar o manual; ela não comprova, por si só, todas as afirmações de um artigo. Os textos com revisão documental identificada apresentam as referências usadas na própria página. As datas de publicação e de atualização são exibidas separadamente quando diferentes.</p><p>Ferramentas de inteligência artificial podem apoiar a redação. Novos textos gerados ficam em rascunho até a revisão editorial e a conferência das fontes. Conteúdos antigos estão sujeitos a correções: comunique divergências com o modelo exato e um documento de referência.</p>
<h2>Autoria e contato</h2><p><Link href="/autores/marcelo-franca/">Marcelo França</Link> é o nome editorial que assina os artigos do projeto. Para informar erro ou sugerir pauta, use a <Link href="/contato/">página de contato</Link>.</p>
<h2>Como o site se mantém</h2><p>Como associado da Amazon, recebemos comissão por compras qualificadas feitas por nossos links. O preço e as condições são definidos pelo vendedor. Leia a <Link href="/afiliados/">política de afiliados</Link>.</p></InstitutionalPage>;}
