import Link from 'next/link';
import ProductCard from '@/components/ProductCard';
import {BreadcrumbSchema,FAQSchema,ItemListSchema} from '@/components/Schema';
import {products} from '@/content/products';
import {faq} from '@/content/faq';
import {site} from '@/lib/site';
import {editorialUpdated,displayDate} from '@/lib/editorial';
import {amazonLink} from '@/lib/amazon';
const guides=[
 ['Capacidade que você consegue secar','Anote a carga que precisa sair pronta em um único ciclo. Se você lava 11 kg, mas a máquina seca 6 kg, será necessário retirar parte das peças ou começar com uma carga menor. A decisão deve partir da secagem quando essa função será usada com frequência.'],
 ['Espaço para instalar e abrir a porta','Meça largura, altura e profundidade do local, além do trajeto de entrada do aparelho. As medidas do gabinete não incluem necessariamente mangueiras e espaço de operação. Reserve as folgas exigidas pelo manual, sem adotar uma distância única para todas as máquinas.'],
 ['Consumo em condições comparáveis','Confira se o consumo informado se refere à lavagem ou à lavagem com secagem. Temperatura, carga e programa alteram o resultado. Para estimar custo, multiplique os kWh do ciclo pelo valor da sua tarifa e pelo número de ciclos previstos no mês.'],
 ['Programas que combinam com suas roupas','Considere os tecidos que você lava: algodão, sintéticos e delicados podem exigir cuidados diferentes. Um ciclo rápido tem restrições de carga e sujeira; ele não equivale necessariamente a um ciclo completo para a capacidade máxima.'],
 ['Vapor e conectividade por modelo','Wi-Fi pode permitir acompanhamento pelo aplicativo, mas as funções disponíveis variam. Vapor pode ter finalidades distintas, como reduzir odores ou complementar um programa. Confira a descrição específica, sem considerar os recursos intercambiáveis entre marcas.'],
 ['Assistência na sua região','Use o canal oficial da marca e informe o modelo e o CEP para localizar atendimento. Não suponha que uma marca atende qualquer cidade ou que peças estarão disponíveis imediatamente. Prazo, cobertura e custo precisam de confirmação.'],
 ['Tensão e instalação elétrica','Confira a tensão na etiqueta do aparelho e a instalação prevista no manual. Versões de 127 V e 220 V não tornam a máquina bivolt. Se houver dúvida sobre tomada, circuito ou aterramento, peça a avaliação de um profissional habilitado.'],
 ['Custo total da compra','Além do preço anunciado, some frete, instalação e eventuais adaptações da lavanderia. Compare o mesmo código e condição de produto. Uma diferença no anúncio pode significar outra cor, capacidade, tensão ou até um modelo distinto.'],
];
const yesNo=v=>v===true?'Sim':v===false?'Não':'Consultar ficha';
export default function HomePage(){return <>
 <BreadcrumbSchema items={[{name:'Início',url:site.url}]}/><ItemListSchema/><FAQSchema items={faq}/>
 <section className="hero"><div className="container"><span className="hero-eyebrow">Guia atualizado em <time dateTime={editorialUpdated}>{displayDate(editorialUpdated)}</time></span><h1>Melhor lava e seca para a sua rotina</h1><p className="hero-sub">Compare {products.length} modelos por capacidade, recursos e limites de uso. Escolha a partir da quantidade de roupa que precisa secar, do espaço da lavanderia e das condições da oferta.</p><div className="hero-ctas"><a href="#comparativo" className="btn btn-primary">Comparar os modelos</a><a href="#guia" className="btn btn-ghost">Entender o que importa</a></div><p className="hero-disclosure">Como associado da Amazon, recebemos comissão por compras qualificadas feitas pelos links deste site, sem custo adicional para você.</p></div></section>
 <section id="ranking" className="section-tight"><div className="container"><div className="summary-card"><h2>Seleção de {products.length} modelos para comparar em 2026</h2><p>Esta seleção usa fichas e manuais dos fabricantes. Os números identificam os itens para facilitar a consulta; a comparação não atribui notas de testes físicos. Veja <Link href="/sobre/">como o conteúdo é elaborado</Link>.</p><ol>{products.map(p=><li key={p.id}><a href={`#${p.slug}`}><strong>{p.name}</strong> — lava {p.capacityWash.toLocaleString('pt-BR')} kg e seca {p.capacityDry} kg</a></li>)}</ol></div></div></section>
 <section className="section"><div className="container"><div className="section-header"><span className="eyebrow">Compare antes de comprar</span><h2>O que muda entre as lava e seca da seleção</h2><p>Confira as diferenças e abra a fonte de cada ficha. A tensão e o código completo devem coincidir com a versão escolhida na loja.</p></div>{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
 <section id="comparativo" className="section section-alt"><div className="container"><div className="section-header"><h2>Comparativo de capacidade, Wi-Fi e vapor</h2><p>“Consultar ficha” indica informação não confirmada para a versão apresentada. No celular, deslize a tabela para ver todas as colunas.</p></div><div className="article-table-scroll" role="region" aria-label="Comparativo de lava e seca" tabIndex="0"><table className="compare-table"><thead><tr><th scope="col">Modelo</th><th scope="col">Lavagem</th><th scope="col">Secagem</th><th scope="col">Wi-Fi</th><th scope="col">Vapor</th><th scope="col">Oferta</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><th scope="row"><a href={`#${p.slug}`}>{p.name}</a></th><td>{p.capacityWash.toLocaleString('pt-BR')} kg</td><td>{p.capacityDry} kg</td><td>{yesNo(p.wifi)}</td><td>{yesNo(p.steam)}</td><td><a href={amazonLink(p)} target="_blank" rel="sponsored nofollow noopener" data-product={p.id}>Ver na Amazon</a></td></tr>)}</tbody></table></div></div></section>
 <section id="guia" className="section"><div className="container"><div className="section-header"><h2>Como escolher a melhor lava e seca</h2><p>A escolha começa pelas necessidades da casa. Use estes critérios para reduzir as opções antes de comparar promoções.</p></div><div className="guide-grid">{guides.map(([title,text],i)=><div className="guide-card" key={title}><span className="num">{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
 <section className="section section-alt"><div className="container-narrow"><h2>Lavagem e secagem: planeje a carga inteira</h2><p>Uma lava e seca reúne duas etapas que têm limites diferentes. A capacidade nominal de lavagem não é uma promessa de secar o mesmo peso. Em uma máquina de 14/8 kg, por exemplo, respeitar o limite de 8 kg é essencial quando você pretende usar o ciclo contínuo.</p><p>Considere também o volume da roupa e as restrições de cada programa. Uma peça volumosa pode ocupar o tambor antes de atingir o peso máximo. A etiqueta do tecido e o manual são as referências para escolher temperatura e secagem.</p><h3>Quando vale comparar com equipamentos separados</h3><p>Uma lavadora e uma secadora independentes podem permitir lavar uma carga enquanto outra seca, mas exigem espaço, instalação e orçamento próprios. Para quem usa a secagem ocasionalmente ou tem pouco espaço, o aparelho combinado pode ser mais conveniente. Compare a sua rotina de ciclos, não apenas a capacidade anunciada.</p><Link href="/blog/lava-e-seca-separada-e-melhor/">Entenda a comparação entre aparelhos combinados e separados</Link></div></section>
 <section id="faq" className="section"><div className="container-narrow"><h2>Perguntas frequentes sobre lava e seca</h2>{faq.map(item=><details className="faq-item" key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>
 <section className="section section-alt"><div className="container-narrow"><h2>Continue pela sua dúvida</h2><ul><li><Link href="/blog/categoria/guias-de-compra/">Guias de compra e comparativos</Link></li><li><Link href="/blog/categoria/instalacao-e-uso/">Instalação, programas e uso diário</Link></li><li><Link href="/blog/categoria/manutencao-e-erros/">Manutenção e códigos de erro</Link></li></ul></div></section>
 </>;}
