export const faq = [
 {q:'Qual é a melhor lava e seca para a minha casa?',a:'Comece pela quantidade de roupa que pretende secar em cada ciclo, pelo espaço disponível e pelo orçamento. Depois compare recursos do modelo exato e a assistência na sua região. Uma máquina com mais funções não será necessariamente a melhor opção para uma rotina menor.'},
 {q:'Posso lavar e secar a carga máxima sem retirar roupas?',a:'Somente quando a carga respeita também o limite de secagem e o programa escolhido. Os modelos desta seleção têm capacidade de secagem menor que a de lavagem. Para um ciclo contínuo, use o menor limite indicado pelo fabricante.'},
 {q:'Uma lava e seca de 11 kg seca 11 kg?',a:'Não presuma isso. A capacidade de lavagem e a de secagem são diferentes. Confira os dois números na ficha: há modelos de 11 kg que secam 6 kg e outros que secam 7 kg.'},
 {q:'Qual é o consumo de energia de uma lava e seca?',a:'O consumo depende do modelo, programa, temperatura e quantidade de roupa. Compare dados medidos no mesmo tipo de ciclo. O consumo informado apenas para lavagem não representa o ciclo completo de lavagem e secagem.'},
 {q:'É possível lavar edredom?',a:'Depende das instruções da etiqueta do edredom, do volume da peça e do programa permitido no manual da máquina. A capacidade em quilos não garante que um edredom volumoso caiba com espaço para movimentação.'},
 {q:'Toda máquina com motor inverter tem Wi-Fi e vapor?',a:'Não. Inverter descreve uma característica do motor. Wi-Fi, vapor e dosagem automática são recursos separados e precisam ser conferidos no modelo completo.'},
 {q:'Lava e seca precisa de saída de ar para fora da casa?',a:'A instalação depende do sistema de secagem. Consulte o manual do modelo para as conexões de água, drenagem e eventuais exigências de ventilação. Não planeje a instalação apenas pela aparência da máquina.'},
 {q:'Como comparar preços com segurança?',a:'Verifique código do produto, tensão, vendedor, condição de novo ou usado, frete e garantia. As ofertas podem mudar; a consulta na loja é necessária antes de concluir a compra.'},
];
