// Perguntas frequentes — usadas na homepage e no FAQ schema.
export const faq = [
  {
    q: 'Qual a melhor lava e seca para comprar em 2026?',
    a: 'A resposta depende do seu perfil de uso, mas três modelos dominam o mercado por mérito técnico. A Samsung WD11M com AddWash lidera o ranking para quem quer o pacote completo: 11kg de lavagem, porta auxiliar AddWash (útil em pelo menos 20% dos ciclos quando você esquece uma peça depois do start), tecnologia Ecobubble que dissolve o sabão antes de entrar no tambor, e motor Digital Inverter com 20 anos de garantia — a maior do segmento. A LG VC4 com AI Direct Drive empata em primeiro lugar para quem valoriza inteligência artificial: o equipamento pesa a carga, identifica o tecido por resistência mecânica e escolhe automaticamente o ciclo ideal entre mais de 20 mil combinações de movimento. Já a Samsung WD13T de 13kg é a melhor opção para famílias maiores, pois comporta edredom de casal com lençóis no mesmo ciclo. Nenhuma das três vai decepcionar — a diferença real está nos recursos que você vai de fato usar no dia a dia, não na ficha técnica.',
  },
  {
    q: 'Lava e seca seca a roupa totalmente ou deixa úmida?',
    a: 'Depende de dois fatores: capacidade de secagem e tipo de tecido. Toda lava e seca tem uma capacidade de secagem menor que a de lavagem — normalmente 60% a 70% do limite nominal. Numa máquina de 11kg (lavagem), a secagem suporta cerca de 7kg. Se você respeitar esse limite, a roupa sai seca, pronta para guardar ou vestir. Se encher até o gargalo da lavagem e mandar secar tudo junto, a roupa sai úmida e amassada — o fluxo de ar quente não consegue circular entre as peças comprimidas. O truque que todo mundo aprende depois de três meses usando o eletrodoméstico: lave a carga completa, retire metade, seque em dois lotes. Para toalhas de banho grossas, mesmo respeitando o peso, pode sobrar uma leve umidade nas costuras — isso é normal e se resolve com o ciclo extra "Secagem por Tempo" de 20 minutos. Tecidos sintéticos (poliéster, lycra) secam mais rápido que algodão, então você pode misturá-los sem ultrapassar o peso total.',
  },
  {
    q: 'Vale a pena comprar lava e seca ou separadas?',
    a: 'Para 90% dos apartamentos e casas com até 3 quartos no Brasil, a lava e seca é a escolha mais racional. O principal argumento é logístico: você coloca a roupa suja, programa e volta horas depois com ela limpa e seca — sem transferir carga molhada de um aparelho para outro, sem ocupar varanda com varal, sem depender do clima. Uma lavadora com secadora integrada ocupa de 65cm x 65cm de piso (contra 130cm lineares de duas máquinas lado a lado), usa uma única tomada de 20A e uma única instalação hidráulica. Para casas com área de serviço grande e famílias de 5+ pessoas que lavam roupa todo dia, o conjunto separado (lavadora + secadora de parede, por exemplo a LG Celo de 17kg + secadora Samsung de 17kg) faz sentido porque você pode lavar uma carga enquanto outra seca, dobrando a produtividade. Mas isso custa no mínimo o dobro e exige instalação 220V bifásica para a secadora. Se você nunca teve uma lava e seca, saiba que a curva de adaptação é de cerca de duas semanas — depois disso você se pergunta como viveu sem.',
  },
  {
    q: 'Quanto de energia uma lava e seca gasta por mês?',
    a: 'Vamos a números reais com base na tarifa média nacional de R$ 0,90/kWh. Um ciclo completo de lavagem + secagem numa lava e seca classe A com motor Inverter (como LG VC4, Samsung WD11M ou Electrolux LSP11) consome entre 1,2 e 2,0 kWh dependendo da temperatura da água e do nível de secagem escolhido. Para uma família de 3 pessoas que lava 3 cargas completas por semana com secagem, o consumo mensal fica entre 18 e 36 kWh — isso representa de R$ 16 a R$ 32 na conta de luz. Para comparação: um chuveiro elétrico de 5500W usado 15 minutos por dia consome cerca de 40 kWh/mês sozinho. Ou seja, o equipamento gasta menos energia que o chuveiro. Modelos sem Inverter ou fabricados antes de 2022 podem consumir o dobro, passando de 50 kWh/mês. Dica prática que reduz a conta: use o ciclo de lavagem com água fria sempre que possível (a resistência elétrica para aquecer água é responsável por 70% do consumo) e programe a secagem para o modo "Armário" ou "Passar" — secar 90% e passar a ferro é mais econômico que secar 100% na máquina. O consumo real também varia por região: no Sul e Sudeste, a tarifa pode chegar a R$ 1,10/kWh, subindo o custo mensal para até R$ 40.',
  },
  {
    q: 'Qual a diferença entre motor Inverter e motor comum?',
    a: 'A diferença está no princípio de funcionamento. Um motor elétrico comum de indução opera em velocidade fixa — ele liga na potência máxima e desliga, repetindo esse ciclo centenas de vezes durante a lavagem. Isso gera trancos, vibração e picos de corrente que estressam tanto o motor quanto a estrutura da máquina. Já o motor Inverter (Digital Inverter na Samsung, AI DD na LG, Inverter na Electrolux) usa um circuito eletrônico que converte a corrente alternada em corrente contínua e depois reconverte em alternada com frequência variável. Na prática: o motor acelera e desacelera suavemente, sem trancos, o que reduz em até 35% o consumo de energia e em pelo menos 6 decibéis o ruído. A diferença de 6 dB pode parecer pequena, mas na escala logarítmica significa metade da pressão sonora percebida. Para quem tem área de serviço próxima a quartos, essa redução é perceptível. Outro ponto crítico: motores Inverter não usam escovas de carvão para transferir corrente — isso elimina uma peça de desgaste programado, permitindo que fabricantes como Samsung ofereçam 20 anos de garantia no motor (contra 2 a 3 anos de um motor comum). Se você está dividido entre dois modelos e um deles tem Inverter, compre o Inverter. Em 2026, qualquer aparelho sem essa tecnologia é obsoleto.',
  },
  {
    q: 'Quanto tempo dura uma lava e seca?',
    a: 'A vida útil de uma máquina lava e seca de qualidade gira em torno de 10 a 15 anos com uso moderado (3 a 5 ciclos semanais) e manutenção preventiva mensal. Os componentes têm durações diferentes: o motor Inverter é praticamente eterno — Samsung cobre 20 anos e LG cobre 10 anos só no motor — porque não tem escovas nem correia (é acoplamento direto). A placa eletrônica de controle dura entre 8 e 12 anos, sendo o item mais sensível a surtos elétricos (por isso um filtro de linha ou estabilizador de R$ 80 pode economizar um reparo de R$ 600). Os amortecedores e molas da suspensão do tambor começam a perder eficiência após 7 a 9 anos, o que se manifesta como vibração excessiva na centrifugação. A resistência elétrica e a bomba de dreno são os primeiros a falhar, geralmente entre 5 e 8 anos, e custam entre R$ 150 e R$ 350 para substituir. A manutenção que prolonga a vida do equipamento é simples e gratuita: limpe o filtro de fiapos a cada 3 ciclos com secagem, execute o ciclo de limpeza do tambor uma vez por mês (a maioria dos modelos tem programa específico para isso), e deixe a porta aberta por 2 horas após cada uso para evaporar a umidade residual que causa mofo na borracha de vedação. Máquinas instaladas em varandas descobertas ou áreas com maresia duram 30% a 40% menos por corrosão dos componentes eletrônicos.',
  },
  {
    q: 'Dá para colocar edredom em lava e seca?',
    a: 'Dá sim, e o resultado é melhor do que lavar em lavadora comum porque a secagem dentro da máquina evita que o edredom fique dias no varal acumulando poeira e ácaros. Mas há regras importantes de capacidade e programa. Um edredom de casal tamanho king (2,40m x 2,20m) pesa entre 3kg e 5kg quando molhado. Se o seu aparelho tem tambor de 10kg ou 11kg (lavagem), você lava e seca o edredom sozinho, sem outras peças, usando o programa específico "Edredom", "Roupa de Cama" ou "Bedding". Esses programas usam maior volume de água, centrifugação mais suave e temperatura controlada para não danificar o enchimento. Em modelos de 13kg como a Samsung WD13T, você consegue incluir lençóis e fronhas no mesmo ciclo porque a capacidade de lavagem sobra. O que você NÃO deve fazer: enfiar edredom em máquina de 8kg ou menor — ele não terá espaço para se movimentar no tambor e a lavagem será superficial. NUNCA use o ciclo de centrifugação máxima para edredom — isso pode deslocar o enchimento interno e criar "bolas" permanentes de fibra. Edredons de pena de ganso exigem cuidado redobrado: só lave em água fria e use o programa "Delicado" com secagem em temperatura baixa para não ressecar as penas. Após o ciclo, estenda o edredom por 2 a 3 horas em local arejado para evaporar qualquer umidade residual — isso previne mofo no guarda-roupa.',
  },
  {
    q: 'Qual capacidade de lava e seca escolher pela família?',
    a: 'A capacidade é a decisão mais importante porque não tem como "expandir" depois que o eletrodoméstico está instalado. A conta é simples mas muita gente erra: 1 pessoa ou casal sem filhos = 8kg a 9kg de lavagem (secagem de 5kg a 6kg), suficiente para 2 a 3 jogos de cama por semana mais roupas pessoais. Família de 2 a 3 pessoas = 10kg a 11kg (secagem 7kg), o ponto ideal de custo-benefício — comporta edredom de casal e dá conta de 3 a 4 lavagens semanais sem aperto. Família de 4 a 5 pessoas = 11kg a 13kg, com prioridade para 13kg se houver crianças pequenas (que geram de 2 a 3 vezes mais roupa suja que um adulto). Família com 6 ou mais pessoas ou quem lava roupa de cama de várias camas por vez = acima de 13kg ou, mais realisticamente, duas máquinas em paralelo. Um erro comum: comprar pela capacidade de lavagem sem olhar a de secagem. Numa lava e seca de 11kg/7kg, se você lavar 11kg de roupa terá que dividir a secagem em dois lotes de aproximadamente 5,5kg cada — isso dobra o tempo total do processo. Por isso famílias de 4+ pessoas se beneficiam mais de um modelo de 13kg/8kg como a Samsung WD13T ou LG VC5 de 13kg, onde 80% das cargas do dia a dia cabem inteiras no ciclo de secagem. Pense na sua rotina real, não na exceção: se você lava edredom duas vezes por ano, comprar uma máquina de 13kg só por isso não faz sentido — melhor usar uma lavanderia nessas duas ocasiões.',
  },
  {
    q: 'Lava e seca Samsung, LG ou Electrolux: qual escolher?',
    a: 'As três marcas dominam 80% do mercado premium brasileiro e todas entregam qualidade, mas cada uma tem personalidade técnica distinta. Samsung se destaca em tecnologia e conectividade: o ecossistema SmartThings permite controlar o eletrodoméstico pelo celular, receber notificação de fim de ciclo e diagnóstico remoto de falhas. A porta AddWash (presente nos modelos WD11M, WD11A e WD13T) é exclusiva da marca e resolve o problema real de esquecer peças após o start. O motor Digital Inverter tem a maior garantia do mundo (20 anos). LG é a referência em engenharia de lavagem: a tecnologia AI Direct Drive analisa o peso, a absorção de água e a resistência têxtil da carga para escolher entre 20 mil combinações de movimento do tambor — isso significa que uma camisa de seda e uma calça jeans na mesma máquina recebem tratamentos diferentes automaticamente. O TurboWash 360 lava uma carga completa em 39 minutos sem sacrificar a limpeza. A LG também é consistentemente a marca mais silenciosa do mercado, com níveis de ruído em centrifugação abaixo de 72 dB. Electrolux é a escolha pragmática: os modelos LSP11 e LSP13 entregam lavagem e secagem eficientes com motor Inverter por um preço de 15% a 25% menor que Samsung e LG equivalentes. A rede de assistência técnica da Electrolux é a mais capilarizada do Brasil, com peças de reposição disponíveis até em cidades médias — enquanto Samsung e LG podem ter fila de espera de 30 a 60 dias para componentes específicos fora das capitais. Se você mora no interior, esse é um fator decisivo.',
  },
  {
    q: 'Qual lava e seca é boa e barata?',
    a: 'O segmento de entrada mudou bastante nos últimos dois anos, e hoje é possível comprar um equipamento decente por menos de R$ 3.500. A Electrolux LSP11 Turbo é minha recomendação principal de custo-benefício: motor Inverter, 11kg de lavagem, 7kg de secagem, programa Turbo que reduz o ciclo em 30%, e a confiabilidade da maior rede de assistência técnica do país. Ela não tem vapor (SteamCare), não tem dispensador automático de sabão e não tem conectividade Wi-Fi — mas lava e seca tão bem quanto modelos que custam R$ 1.500 a mais. Se o orçamento for ainda mais apertado (faixa de R$ 2.500 a R$ 3.000), a Midea MF200D de 10kg é uma alternativa honesta: o acabamento é mais simples, o painel é menos intuitivo e a durabilidade estimada é de 6 a 8 anos contra 10+ das marcas premium, mas para uso doméstico normal de solteiro ou casal sem filhos, ela cumpre a função sem sustos. O que você sacrifica ao descer de faixa de preço: nível de ruído (modelos de entrada são 5 a 8 dB mais barulhentos), qualidade dos amortecedores (mais vibração após 3-4 anos de uso), eficiência energética (classe B em vez de A) e disponibilidade de peças de reposição a longo prazo (7-10 anos após o lançamento). Minha sugestão: se couber no orçamento, prefira um modelo de marca consolidada (Electrolux, Samsung, LG) mesmo que seja o de entrada da linha, em vez de um modelo "cheio de recursos" de uma marca sem tradição em lavanderia. A lava e seca é um aparelho que você vai usar por pelo menos 8 anos — R$ 500 a mais diluídos nesse período custam R$ 5 por mês.',
  },
  {
    q: 'Posso instalar lava e seca em qualquer lugar?',
    a: 'Não, e muitos compradores descobrem isso da pior forma: com o entregador na porta e a máquina não passando na escada ou o ponto elétrico inadequado. Requisitos essenciais: (1) Tomada de 20 amperes, exclusiva para o aparelho — não divida com micro-ondas ou geladeira no mesmo disjuntor, pois a corrente de partida da centrifugação pode desarmar o circuito. (2) Tensão 127V ou 220V depende do modelo — em 2026, a maioria das lava e seca Samsung e LG é bivolt automática (110V/220V), mas sempre confirme na ficha técnica antes de comprar. (3) Ponto de água fria com pressão entre 1 e 10 metros de coluna de água (m.c.a.) — se você mora em andar alto de prédio antigo com pressão fraca, pode precisar de um pressurizador. (4) Ralo ou sifão a no máximo 1,5 metro de distância da saída de drenagem da máquina e a uma altura entre 60cm e 90cm do chão — a drenagem da lava e seca é por gravidade e mangueira de escoamento. (5) Espaço físico: a máquina mede em média 65cm de largura x 65cm de profundidade x 85cm de altura. Deixe folga de 3cm nas laterais e 5cm atrás para ventilação e acesso às mangueiras. (6) Peso: o eletrodoméstico pesa entre 75kg e 95kg vazio — um piso de madeira ou porcelanato sobre laje suporta, mas um piso suspenso de quarto no andar superior pode vibrar. Idealmente, instale no térreo ou sobre laje de concreto. NUNCA instale em varanda descoberta: a umidade da chuva oxida a placa eletrônica (reparo de R$ 800 a R$ 1.200) e o sol direto resseca a borracha da porta em 2 a 3 anos, causando vazamentos. Se a varanda for coberta e fechada com vidro, pode instalar sem problemas. Por fim, meça TODAS as portas e corredores do percurso da rua até o local de instalação — a largura mínima de passagem é 70cm, mas o ideal é 75cm para manobrar.',
  },
  {
    q: 'O que é a função AddWash da Samsung?',
    a: 'É uma porta secundária embutida na porta principal que permite adicionar peças de roupa ou mais sabão depois que o ciclo de lavagem já começou, sem precisar desligar a máquina, esperar o tambor destravar e recomeçar do zero. A engenharia por trás é inteligente: ao abrir a portinha, a lava e seca pausa automaticamente a entrada de água e o giro do tambor, mas mantém a água já acumulada dentro da cuba. Você adiciona a peça esquecida, fecha a portinha, e a máquina retoma o ciclo exatamente de onde parou — sem drenar a água, sem reiniciar o programa, sem desperdício. Na prática, isso resolve o cenário que acontece em pelo menos 20% dos ciclos domésticos: você deu start, foi para outro cômodo e achou uma meia no chão, uma camiseta caída atrás do cesto ou lembrou que o tênis também precisava lavar. Sem AddWash, você teria que desligar tudo, abrir a porta principal (perdendo a água que já entrou), recolocar a peça e iniciar um novo ciclo. Com AddWash, são 10 segundos. A função está disponível nos modelos Samsung WD11M, WD11A, WD13T e WD10M. Existe uma limitação: a portinha só funciona na fase de lavagem e enxágue — durante a secagem, o sistema trava por segurança, pois abrir a porta liberaria ar a 60°C-80°C. Não é um "gadget" supérfluo: depois de um mês usando, você percebe que usa AddWash quase toda semana. É o tipo de recurso que, uma vez experimentado, vira critério de compra.',
  },
  {
    q: 'Lava e seca gasta muita água?',
    a: 'Ao contrário do senso comum, o aparelho consome menos água que uma lavadora convencional de capacidade equivalente. Uma máquina lava e seca moderna de 11kg gasta entre 50 e 90 litros por ciclo completo de lavagem — isso é 20% a 30% menos que uma lavadora tanquinho ou lava-roupas comum de mesma capacidade, que consome de 90 a 150 litros por ciclo. A economia vem de dois fatores: o tambor horizontal (em vez de agitador vertical) usa a gravidade para mover a roupa pela água, então precisa de menos volume para saturar a carga; e o sistema de recirculação de água que algumas marcas usam (a LG chama de 6 Motion, a Samsung de AquaPreserve) filtra e reutiliza parte da água do enxágue. A secagem não consome água nenhuma — é um ciclo puramente térmico e mecânico: a resistência elétrica aquece o ar, um ventilador interno sopra esse ar quente através da roupa girando no tambor, a umidade evapora e condensa em uma câmara fria (ou é expelida como vapor em modelos com saída de ar), e a água condensada vai para o ralo. Na tecnologia Ecobubble da Samsung, a economia é ainda maior porque o sabão é pré-misturado com água e ar antes de entrar no tambor, criando uma espuma densa que penetra os tecidos mais rápido — isso reduz em até 30% o consumo de água e 20% o de energia em comparação com a lavagem convencional. Para referência: 70 litros de água representam cerca de duas descargas de vaso sanitário econômico ou 10 minutos de chuveiro. Em uma casa com 3 pessoas que lavam roupa 4 vezes por semana, o gasto mensal de água da lava e seca é de aproximadamente 1.200 litros — menos de R$ 10 na conta de água na maioria das cidades brasileiras.',
  },
  {
    q: 'Qual programa usar para cada tipo de roupa?',
    a: 'A maioria das pessoas usa apenas 2 ou 3 programas por anos, mas a máquina lava e seca moderna tem de 12 a 20 ciclos específicos que fazem diferença real na conservação das roupas e na economia. Algodão e roupas do dia a dia (camisetas, calças, cuecas, meias): use o ciclo Algodão a 40°C — essa temperatura dissolve gordura corporal e suor sem agredir as fibras como a água a 60°C faria. Camisas sociais e blusas de tecido fino: ciclo Delicado ou Sintético a 30°C com centrifugação reduzida (800 rpm) para evitar que as dobras do tecido se transformem em vincos difíceis de passar. Jeans e tecidos pesados: ciclo Jeans ou Pesado a 30°C — a temperatura é baixa para não desbotar o índigo, mas a agitação do tambor é mais intensa para remover a sujeira incrustada. Roupa de cama, toalhas de banho e edredons: ciclo Bedding ou Roupa Grande a 40°C ou 60°C — a temperatura mais alta (60°C) elimina ácaros e bactérias que sobrevivem na lavagem a frio, crucial para quem tem rinite ou alergia. Roupa íntima e lingerie: ciclo Delicado ou Intimo com água fria (20°C) e centrifugação mínima (400-600 rpm) para não deformar o elastano. Roupa de bebê: ciclo Bebê ou Higiene a 60°C com vapor (Steam/SteamCare), que elimina 99,9% de bactérias, ácaros e alérgenos sem produtos químicos adicionais — o vapor penetra as fibras e esteriliza termicamente. Quando estiver em dúvida ou com uma carga mista: use o ciclo Automático, Sensor ou AI Wash (LG). Esses programas pesam a carga, medem a turbidez da água (quantidade de sujeira dissolvida) e ajustam automaticamente temperatura, volume de água, tempo de lavagem e intensidade de centrifugação. O resultado raramente é inferior a um programa específico mal escolhido. E uma dica que vale ouro: NUNCA use amaciante em toalhas de banho — o amaciante cria uma película hidrofóbica nas fibras do algodão que reduz a absorção de água. Toalha boa se lava só com sabão e eventualmente uma colher de vinagre branco no enxágue.',
  },
  {
    q: 'É possível usar lava e seca sem sabão líquido?',
    a: 'Sim, 100% das lava e seca aceitam sabão em pó, e em muitos casos ele é até mais eficiente para remover manchas de terra, grama e gordura. A diferença prática está na dissolução e na compatibilidade com recursos avançados. O sabão em pó precisa de água a pelo menos 30°C para se dissolver completamente — em lavagens com água fria, grânulos não dissolvidos podem grudar na borracha da porta e eventualmente causar mofo, ou pior, deixar resíduos brancos visíveis em roupas escuras. Para evitar isso, dilua o sabão em pó em um pouco de água morna antes de colocar no dispensador, ou prefira lavar com temperatura mínima de 30°C. O sabão líquido, por outro lado, se dissolve instantaneamente em qualquer temperatura e é o formato ideal para os sistemas de dosagem automática presentes em modelos como Samsung WD11A (Auto Dispense), LG VC4 e algumas Electrolux topo de linha — nesses equipamentos, você abastece o reservatório a cada 20 a 30 ciclos e a máquina dosa sozinha a quantidade exata baseada no peso da carga, tipo de tecido e nível de sujeira detectado. Isso elimina o erro humano de colocar sabão demais (que deixa resíduo nas roupas e na máquina) ou de menos (que não limpa direito). Um detalhe que quase ninguém sabe: o sabão em pó contém branqueadores ópticos e agentes anti-redeposição que o sabão líquido nem sempre tem, então para roupa branca de algodão (lençóis, toalhas), o sabão em pó pode entregar um resultado mais alvo. Para roupa colorida e escura, o sabão líquido específico para cores preserva melhor o tingimento. Minha recomendação: mantenha os dois formatos em casa e alterne conforme a carga — pó para roupa branca e de cama, líquido para roupas coloridas e cargas com dosagem automática. E para quem tem pele sensível: o sabão líquido costuma enxaguar mais completamente, deixando menos resíduo químico no tecido, o que reduz o risco de dermatite de contato.',
  },
];
