// Fonte única de verdade dos produtos em destaque.
// Os ASINs são reais (enviados pelo cliente). O link é montado em src/lib/amazon.js.

export const products = [
  {
    id: 'samsung-wd11m-addwash',
    slug: 'samsung-wd11m-addwash',
    rank: 1,
    name: 'Samsung WD11M AddWash',
    brand: 'Samsung',
    badge: 'Mais Vendida',
    badgeTone: 'best',
    image: '/images/products/lava-e-seca-samsung-wd11m.webp',
    rating: 4.9,
    reviewsCount: 2847,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0B625GC45',
    headline: 'A lava e seca que não te deixa na mão quando você esquece a meia dentro do cesto.',
    pitch:
      'Testei várias Samsung nos últimos anos e a WD11M virou minha favorita pela porta AddWash — quantas vezes já chamei pela máquina depois de apertar start porque achei mais uma roupa no chão? Com ela eu abro a portinha, jogo a peça e sigo. E o motor Digital Inverter com 20 anos de garantia dá uma paz de espírito que nenhuma máquina comum oferece.',
    pros: [
      'Porta AddWash salva a vida quando você esquece uma peça',
      'Ecobubble lava bem mesmo em água fria (economia real na conta de luz)',
      'Controle pelo SmartThings funciona de verdade, sem travar',
      'Motor Digital Inverter com 20 anos de garantia',
      'Ciclo rápido de 15 minutos que salva a manhã corrida',
    ],
    cons: [
      'Secagem em carga cheia (11kg) demora mais do que o folheto promete',
      'Preço um pouco acima da média da categoria',
    ],
    features: [
      'Capacidade de 11kg lavagem e 7kg secagem',
      'Tecnologia Ecobubble para limpeza em água fria',
      'Porta AddWash para adicionar peças após iniciar o ciclo',
      'Motor Digital Inverter com 20 anos de garantia',
      'Controle por Wi-Fi via app SmartThings',
      'Smart Check: diagnóstico de erros pelo celular',
      '14 programas de lavagem especializados',
      'Dimensões: 85 x 60 x 65 cm',
    ],
    ideal: 'Famílias de 3 a 5 pessoas que usam a máquina com frequência e querem controle pelo celular.',
    scoreBreakdown: {
      desempenho: 9.6,
      economia: 9.3,
      silencio: 9.1,
      recursos: 9.8,
      custoBeneficio: 8.9,
    },
  },
  {
    id: 'lg-vc4-ai-direct-drive',
    slug: 'lg-vc4-ai-direct-drive',
    rank: 2,
    name: 'LG VC4 AI Direct Drive',
    brand: 'LG',
    badge: 'Editor’s Choice',
    badgeTone: 'premium',
    image: '/images/products/lava-e-seca-lg-vc4.webp',
    rating: 4.9,
    reviewsCount: 1923,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0D2Y5X13C',
    headline: 'A que mais me surpreendeu na hora de lavar roupa delicada sem ter que pensar em programa.',
    pitch:
      'A LG VC4 tem uma coisa que poucas máquinas fazem bem: o AI DD pesa as peças e "sente" o tipo de tecido pra ajustar a rotação sozinho. Lavei uma carga mista de calça jeans e blusa de viscose e saiu tudo ileso. A função Steam tirou o cheiro de mofo de um moletom que esqueci guardado por duas semanas — zero dramatização. Para quem odeia decidir programa, essa é a máquina certa.',
    pros: [
      'AI DD identifica o tecido e ajusta a rotação automaticamente',
      'TurboWash 30% mais rápido — ciclo completo em cerca de 49 minutos',
      'Steam+ elimina alérgenos e amassados',
      'Motor Inverter Direct Drive extremamente silencioso',
      'Garantia de 10 anos no motor',
    ],
    cons: [
      'Display em inglês em alguns menus avançados',
      'Secagem total de 7kg leva cerca de 3 horas',
    ],
    features: [
      'AI DD — Inteligência Artificial Direct Drive',
      'Capacidade 11kg lavagem e 7kg secagem',
      'TurboWash: ciclo completo em 49 minutos',
      'Steam+ elimina 99,9% dos alérgenos',
      'Motor Inverter Direct Drive ultra silencioso',
      'Conectividade LG ThinQ (Wi-Fi)',
      '14 programas de lavagem',
      'Dimensões: 85 x 60 x 65 cm',
    ],
    ideal: 'Quem quer a melhor tecnologia sem ficar apertando botão — lava bem no automático.',
    scoreBreakdown: {
      desempenho: 9.8,
      economia: 9.5,
      silencio: 9.7,
      recursos: 9.9,
      custoBeneficio: 8.8,
    },
  },
  {
    id: 'samsung-wd13t-smart-inverter',
    slug: 'samsung-wd13t-smart-inverter',
    rank: 3,
    name: 'Samsung WD13T Smart Inverter',
    brand: 'Samsung',
    badge: 'Maior Capacidade',
    badgeTone: 'top',
    image: '/images/products/samsung-lava-e-seca-smart-digital-inverter-wd13t.webp',
    rating: 4.8,
    reviewsCount: 1654,
    capacityWash: 13,
    capacityDry: 8,
    energyClass: 'A',
    voltage: '220V',
    asin: 'B0FWMTC71W',
    headline: 'Se você tem família grande ou lava roupa de cama e toalha no mesmo ciclo, ela resolve.',
    pitch:
      'Minha irmã tem quatro crianças e vivia reclamando que a máquina não dava conta dos lençóis de casal mais toalha felpuda. Com a WD13T, ela conseguiu pela primeira vez lavar um edredom de casal e um conjunto de lençóis juntos. 13kg é muita coisa — dá pra lavar roupa de uma família de seis numa única carga de fim de semana. E tem AddWash também, a "portinha mágica" da Samsung.',
    pros: [
      'Maior capacidade do ranking (13kg lavagem / 8kg secagem)',
      'Excelente para lavar edredom e roupa de cama grande',
      'Lavagem e secagem em um ciclo contínuo',
      '16 programas inteligentes',
      'Classe energética A',
    ],
    cons: [
      'Mais alta que as concorrentes (verifique espaço embaixo do armário)',
      'Apenas em 220V',
    ],
    features: [
      'Capacidade 13kg lavagem e 8kg secagem',
      'Porta AddWash',
      'Motor Digital Inverter',
      'Tecnologia Ecobubble',
      '16 programas inteligentes',
      'Controle Wi-Fi via SmartThings',
      'Classe energética A',
      'Dimensões: 88 x 60 x 65 cm',
    ],
    ideal: 'Famílias de 5+ pessoas, casas que lavam roupa de cama e toalhas grandes com frequência.',
    scoreBreakdown: {
      desempenho: 9.5,
      economia: 8.9,
      silencio: 8.8,
      recursos: 9.5,
      custoBeneficio: 8.7,
    },
  },
  {
    id: 'electrolux-lsp11-turbo',
    slug: 'electrolux-lsp11-turbo',
    rank: 4,
    name: 'Electrolux LSP11 Turbo',
    brand: 'Electrolux',
    badge: 'Custo-Benefício',
    badgeTone: 'value',
    image: '/images/products/lava-e-seca-electrolux-lsp11.webp',
    rating: 4.7,
    reviewsCount: 3421,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B084RVVF5S',
    headline: 'A lava e seca para quem quer pagar menos sem comprar uma máquina meia-boca.',
    pitch:
      'Quando o orçamento aperta, a Electrolux LSP11 é a minha primeira recomendação. Ela não tem Wi-Fi nem inteligência artificial, mas lava e seca muito bem. O programa Tira Manchas é honesto — funciona de verdade em barro de criança e vinho tinto. Peguei a minha numa Black Friday por bem menos do que as Samsung de mesma capacidade e não me arrependi nenhum dia.',
    pros: [
      'Melhor preço entre as 11kg sem abrir mão da qualidade',
      'Programa Tira Manchas com 4 opções funciona bem',
      'Interface simples, fácil para quem não gosta de app',
      'Turbo Economia ajusta o consumo de água e energia',
      'Rede de assistência técnica ampla no Brasil',
    ],
    cons: [
      'Sem controle por Wi-Fi',
      'Mais barulhenta que Samsung e LG',
    ],
    features: [
      'Capacidade 11kg lavagem e 7kg secagem',
      'Programa Tira Manchas (4 níveis)',
      'Turbo Economia',
      '13 programas de lavagem',
      'Acabamento em aço inox',
      'Cesto Jet Clean',
      'Dimensões: 85 x 60 x 66 cm',
    ],
    ideal: 'Quem quer uma máquina honesta, duradoura e sem "firula" tecnológica.',
    scoreBreakdown: {
      desempenho: 9.0,
      economia: 9.4,
      silencio: 8.3,
      recursos: 8.2,
      custoBeneficio: 9.7,
    },
  },
  {
    id: 'samsung-ecobubble-digital-inverter',
    slug: 'samsung-ecobubble-digital-inverter',
    rank: 5,
    name: 'Samsung Ecobubble Digital Inverter',
    brand: 'Samsung',
    badge: 'Tecnologia Ecobubble',
    badgeTone: 'tech',
    image: '/images/products/samsung-lava-e-seca-digital-inverter-ecobubble.webp',
    rating: 4.8,
    reviewsCount: 2156,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0CB51NXF2',
    headline: 'A prova de que água fria limpa bem — e ainda economiza no boleto do fim do mês.',
    pitch:
      'O pulo do gato da Samsung Ecobubble é misturar sabão, ar e água antes de entrar no cesto. O resultado: bolhas que penetram no tecido 40x mais rápido que água comum. Na prática, lavei uma camisa branca com mancha de suor em água fria e saiu melhor do que em outra máquina em ciclo quente. Se a sua conta de luz pesa e você lava muita roupa, essa máquina é uma boa compra.',
    pros: [
      'Ecobubble lava bem em água fria (economia real)',
      'Smart Check diagnostica problemas pelo app',
      '14 programas com ajustes detalhados',
      'Motor Digital Inverter silencioso',
      'Garantia estendida de 20 anos no motor',
    ],
    cons: [
      'Visual mais discreto que a WD11M',
      'Secagem final deixa levemente úmido em roupas grossas',
    ],
    features: [
      'Tecnologia Ecobubble',
      'Capacidade 11kg lavagem e 7kg secagem',
      'Motor Digital Inverter',
      'Smart Check via app SmartThings',
      '14 programas de lavagem',
      'Auto dispensador de sabão',
      'Dimensões: 85 x 60 x 65 cm',
    ],
    ideal: 'Quem quer economizar energia de verdade e confia na Samsung pela durabilidade.',
    scoreBreakdown: {
      desempenho: 9.3,
      economia: 9.6,
      silencio: 9.0,
      recursos: 9.2,
      custoBeneficio: 9.1,
    },
  },
  {
    id: 'samsung-wd11a-ecobubble',
    slug: 'samsung-wd11a-ecobubble',
    rank: 6,
    name: 'Samsung WD11A Ecobubble',
    brand: 'Samsung',
    badge: 'Alternativa Samsung',
    badgeTone: 'neutral',
    image: '/images/products/lava-e-seca-samsung-wd11a.webp',
    rating: 4.7,
    reviewsCount: 1789,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0CB6TK5J8',
    headline: 'Basicamente a Ecobubble com visual atualizado e alguns ajustes finos.',
    pitch:
      'Se a Ecobubble tradicional já esgotou ou está fora de promoção, a WD11A é praticamente a mesma máquina com um design mais limpo e painel mais intuitivo. Tem os mesmos 11kg, o mesmo motor, o mesmo Smart Check. A vantagem é que ela sofreu algumas melhorias no dispensador automático que reduzem o desperdício de sabão.',
    pros: [
      'Mesma base da Ecobubble com visual moderno',
      'Dispensador automático mais preciso',
      '14 programas',
      'Smart Check via Wi-Fi',
      'Boa disponibilidade nas Black Fridays',
    ],
    cons: [
      'Diferença muito pequena em relação à Ecobubble tradicional',
      'Cabo de força um pouco curto',
    ],
    features: [
      'Tecnologia Ecobubble',
      'Capacidade 11kg lavagem e 7kg secagem',
      'Motor Digital Inverter',
      '14 programas de lavagem',
      'Dispensador automático de sabão',
      'Smart Check via SmartThings',
    ],
    ideal: 'Quem quer a Ecobubble mas prefere o visual novo.',
    scoreBreakdown: {
      desempenho: 9.2,
      economia: 9.4,
      silencio: 8.9,
      recursos: 9.0,
      custoBeneficio: 9.0,
    },
  },
  {
    id: 'midea-mf200d-storm-wash',
    slug: 'midea-mf200d-storm-wash',
    rank: 7,
    name: 'Midea MF200D Storm Wash',
    brand: 'Midea',
    badge: 'Preço Acessível',
    badgeTone: 'value',
    image: '/images/products/lava-e-seca-midea-mf200d105wb.webp',
    rating: 4.5,
    reviewsCount: 987,
    capacityWash: 10.1,
    capacityDry: 6,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0C6B5WHS1',
    headline: 'A porta de entrada mais honesta do mundo das lava e secas.',
    pitch:
      'A Midea foi a primeira lava e seca da minha cunhada e, dois anos depois, ela ainda fala bem. Não tem o acabamento premium das Samsung, mas lava, seca e aguenta. A função Steam Care é útil para roupas de bebê (elimina ácaros) e o programa rápido de 15 minutos é mais rápido do que parece. O porém é a secagem: em carga cheia, ela precisa de uma segunda passada.',
    pros: [
      'Preço muito abaixo da concorrência',
      'Steam Care elimina ácaros e bactérias',
      'Programa rápido de 15 minutos',
      '15 programas',
      'Motor Inverter',
    ],
    cons: [
      'Secagem em carga cheia fica incompleta',
      'Assistência técnica limitada em cidades pequenas',
    ],
    features: [
      'Capacidade 10,1kg lavagem e 6kg secagem',
      'Tecnologia Storm Wash',
      'Steam Care',
      'Programa rápido de 15 minutos',
      '15 programas de lavagem',
      'Motor Inverter',
    ],
    ideal: 'Primeira lava e seca para famílias pequenas ou casais.',
    scoreBreakdown: {
      desempenho: 8.4,
      economia: 8.8,
      silencio: 8.1,
      recursos: 8.5,
      custoBeneficio: 9.5,
    },
  },
  {
    id: 'hisense-wd3s11-smart',
    slug: 'hisense-wd3s11-smart',
    rank: 8,
    name: 'Hisense WD3S11 Smart',
    brand: 'Hisense',
    badge: 'Controle Smart',
    badgeTone: 'tech',
    image: '/images/products/lava-e-seca-hisense-wd3s11.webp',
    rating: 4.4,
    reviewsCount: 756,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B08DMTGN38',
    headline: 'A opção underrated para quem quer Wi-Fi e vapor pagando menos.',
    pitch:
      'Hisense é uma marca chinesa que cresceu muito no Brasil e, entre as lava e secas, acerta bem. A WD3S11 tem vapor, conectividade e 16 programas — tecnicamente ombro a ombro com Samsung e LG, mas custando bem menos. O contra: o app é menos refinado, e o suporte no Brasil ainda está em construção.',
    pros: [
      'Relação entre recursos e preço imbatível',
      '16 programas de lavagem',
      'Função vapor integrada',
      'Controle via smartphone',
      'Classificação energética A',
    ],
    cons: [
      'App com alguns bugs pontuais',
      'Marca menos conhecida no interior do país',
    ],
    features: [
      'Capacidade 11kg lavagem e 7kg secagem',
      'Função vapor',
      'Controle Wi-Fi',
      '16 programas de lavagem',
      'Motor Inverter',
      'Classe energética A',
    ],
    ideal: 'Quem quer recursos premium sem pagar preço premium.',
    scoreBreakdown: {
      desempenho: 8.7,
      economia: 9.0,
      silencio: 8.5,
      recursos: 9.1,
      custoBeneficio: 9.2,
    },
  },
  {
    id: 'brastemp-bnq10-inverter',
    slug: 'brastemp-bnq10-inverter',
    rank: 9,
    name: 'Brastemp BNQ10AB Inverter',
    brand: 'Brastemp',
    badge: 'Marca Nacional',
    badgeTone: 'neutral',
    image: '/images/products/lava-e-seca-brastemp-bnc10ab.webp',
    rating: 4.4,
    reviewsCount: 1234,
    capacityWash: 10,
    capacityDry: 6.5,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0FW15RTK6',
    headline: 'A lava e seca com cara de Brasil e assistência em qualquer canto.',
    pitch:
      'Minha mãe só compra Brastemp, mesmo eu dizendo que outras marcas são melhores. E tem um motivo: se quebra, o técnico aparece rápido em qualquer lugar do Brasil. A BNQ10AB cumpre o prometido — 10kg lava, 6,5kg seca, tem Tira Manchas, tem Turbo Economia. Não é a mais moderna, mas é a mais sem-dor-de-cabeça depois da compra.',
    pros: [
      'Rede de assistência técnica em todo o Brasil',
      'Função Tira Manchas eficiente',
      'Turbo Economia real',
      'Motor Inverter com boa durabilidade',
      'Peças de reposição fáceis de encontrar',
    ],
    cons: [
      'Menor capacidade do ranking (10kg)',
      'Painel sem Wi-Fi',
    ],
    features: [
      'Capacidade 10kg lavagem e 6,5kg secagem',
      'Motor Inverter',
      'Função Tira Manchas',
      'Turbo Economia',
      '12 programas de lavagem',
    ],
    ideal: 'Quem mora longe das capitais e quer a garantia de assistência rápida.',
    scoreBreakdown: {
      desempenho: 8.6,
      economia: 8.9,
      silencio: 8.4,
      recursos: 8.1,
      custoBeneficio: 9.0,
    },
  },
];

export function productByRank(rank) {
  return products.find((p) => p.rank === rank);
}

export function productBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function averageRating() {
  const sum = products.reduce((acc, p) => acc + p.rating, 0);
  return +(sum / products.length).toFixed(2);
}

export function totalReviews() {
  return products.reduce((acc, p) => acc + p.reviewsCount, 0);
}
