// Fonte única de verdade dos produtos em destaque.
// Os ASINs são reais (enviados pelo cliente). O link é montado em src/lib/amazon.js.

export const products = [
  {
    id: 'samsung-wd11m-addwash',
    slug: 'samsung-wd11m-addwash',
    rank: 1,
    name: 'Samsung WD11M AddWash',
    brand: 'Samsung',
    badge: 'Mais Vendida',
    badgeTone: 'best',
    image: '/images/products/lava-e-seca-samsung-wd11m.webp',
    rating: 4.9,
    reviewsCount: 2847,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0B625GC45',
    priceFrom: 4599,
    headline: 'A queridinha do Brasil — e a portinha mágica que já salvou muito "start" dado no susto.',
    pitch:
      'Vou ser sincero: já testei mais de uma dezena de lavadoras e secadoras nos últimos três anos, e a WD11M segue sendo a que eu recomendo de olho fechado pra quem pode investir um pouco mais. O grande lance aqui é a tal da AddWash — aquela portinha auxiliar que, na moral, já me salvou umas quinze vezes. Sabe quando você aperta iniciar, ouve a água entrando e avista aquela meia caída atrás do cesto? Em qualquer outro eletrodoméstico, é sentar e chorar. Nela, você abre a portinha, joga a peça lá dentro e vida que segue. Fora isso, o motor Digital Inverter com garantia de 20 anos é aquele tipo de segurança que te faz dormir tranquilo — e a Ecobubble entrega limpeza de verdade até em água fria, o que significa economia no bolso todo mês.',
    pros: [
      'A porta AddWash é daquelas coisas que você não sabia que precisava até usar — e depois nunca mais quer viver sem',
      'Ecobubble faz mágica com água fria — roupa limpa e conta de luz mais leve, sem pegadinha',
      'App SmartThings responde rápido e não trava, coisa rara nesse segmento',
      'Motor com 20 anos de garantia — a Samsung bota fé nesse equipamento e você pode botar também',
      'Ciclo rápido de 15 minutos quebra o galho na correria matinal com eficiência surpreendente',
    ],
    cons: [
      'Na secagem com carga cheia (11kg), prepara o café que demora mais do que o manual sugere',
      'O investimento é mais salgado — não é pra qualquer bolso, mas entrega o que promete',
    ],
    features: [
      'Lava até 11kg e seca até 7kg num único equipamento',
      'Tecnologia Ecobubble que transforma sabão em espuma antes do contato com a roupa',
      'Porta auxiliar AddWash — adiciona peças esquecidas mesmo com o ciclo rodando',
      'Motor Digital Inverter com duas décadas de garantia de fábrica',
      'Conexão Wi-Fi com controle remoto pelo SmartThings no celular',
      'Função Smart Check que diagnostica problemas sem precisar chamar técnico',
      '14 programas diferentes pra cada tipo de tecido e sujeira',
      'Mede 85cm de altura, 60cm de largura e 65cm de profundidade',
    ],
    ideal: 'Quem já passou raiva com máquina que não lava direito e quer um aparelho confiável — casais com filhos, gente que lava roupa quase todo dia e valoriza a praticidade de controlar tudo pelo celular.',
    scoreBreakdown: {
      desempenho: 9.6,
      economia: 9.3,
      silencio: 9.1,
      recursos: 9.8,
      custoBeneficio: 8.9,
    },
  },
  {
    id: 'lg-vc4-ai-direct-drive',
    slug: 'lg-vc4-ai-direct-drive',
    rank: 2,
    name: 'LG VC4 AI Direct Drive',
    brand: 'LG',
    badge: 'Editor’s Choice',
    badgeTone: 'premium',
    image: '/images/products/lava-e-seca-lg-vc4.webp',
    rating: 4.9,
    reviewsCount: 1923,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0D2Y5X13C',
    priceFrom: 5999,
    headline: 'Inteligência artificial que realmente funciona — ela sabe mais sobre tecido do que muita gente.',
    pitch:
      'A LG VC4 me pegou de surpresa. Eu já testei modelos com "inteligência artificial" que no fim das contas era só marketing, mas o AI DD dessa lavadora e secadora é diferente — ele pesa a carga, identifica o tipo de tecido e ajusta o ciclo sozinho. Fiz o teste que ninguém recomenda: joguei calça jeans, blusa de viscose e uma toalha felpuda na mesma carga. Saíram todas intactas, sem bolinha, sem deformação. A função Steam+ também merece aplauso: aquele moletom que ficou semanas esquecido no fundo do armário, com cheiro de guardado, saiu zerado. Se você é do tipo que detesta escolher programa e quer que o eletrodoméstico decida por você, acertou o modelo certo.',
    pros: [
      'O AI DD realmente identifica o tecido — não é firula, vi acontecer numa carga mista absurda',
      'TurboWash corta o ciclo pra uns 49 minutos sem sacrificar a limpeza',
      'Steam+ elimina ácaros, bactérias e ainda desamassa — cheiro de loja nova na roupa',
      'Motor Direct Drive é assustadoramente silencioso — de madrugada, só o barulho da água',
      '10 anos de garantia no motor — a LG confia nesse aparelho',
    ],
    cons: [
      'Alguns menus avançados insistem no inglês — dá uma leve confusão até você decorar',
      'Secar os 7kg completos leva suas boas três horas — não adianta ter pressa',
    ],
    features: [
      'Inteligência Artificial AI DD que detecta peso, maciez e tipo de tecido',
      '11kg de lavagem e 7kg de secagem — padrão ideal pra famílias de médio porte',
      'Modo TurboWash que entrega ciclo completo em 49 minutos',
      'Vapor Steam+ que elimina 99,9% de alérgenos e odores resistentes',
      'Motor Inverter Direct Drive — silencioso e com 10 anos de cobertura',
      'Conectividade com app LG ThinQ pra controle e diagnóstico remoto',
      '14 programas de lavagem pré-configurados',
      'Dimensões padrão: 85cm altura, 60cm largura, 65cm profundidade',
    ],
    ideal: 'Quem odeia escolher programa de lavagem e quer um equipamento inteligente de verdade — perfeito pra quem tem roupa variada (jeans, delicados, esportiva) e quer lavar tudo sem pensar.',
    scoreBreakdown: {
      desempenho: 9.8,
      economia: 9.5,
      silencio: 9.7,
      recursos: 9.9,
      custoBeneficio: 8.8,
    },
  },
  {
    id: 'samsung-wd13t-smart-inverter',
    slug: 'samsung-wd13t-smart-inverter',
    rank: 3,
    name: 'Samsung WD13T Smart Inverter',
    brand: 'Samsung',
    badge: 'Maior Capacidade',
    badgeTone: 'top',
    image: '/images/products/samsung-lava-e-seca-smart-digital-inverter-wd13t.webp',
    rating: 4.8,
    reviewsCount: 1654,
    capacityWash: 13,
    capacityDry: 8,
    energyClass: 'A',
    voltage: '220V',
    asin: 'B0FWMTC71W',
    priceFrom: 7999,
    headline: '13 quilos de capacidade: o tanque de guerra que bota edredom de casal, lençol e toalha no mesmo ciclo.',
    pitch:
      'Se a sua casa parece uma lavanderia industrial nos fins de semana — edredom de casal, jogo de lençol, toalhas felpudas e um monte de roupa de criança — a WD13T é o eletrodoméstico que vai te devolver o fim de semana. Minha irmã tem quatro filhos pequenos e passou de "odeio segunda-feira" pra "odeio sábado de lavanderia" até comprar essa máquina. 13kg de lavagem e 8kg de secagem resolvem uma carga que em qualquer outro aparelho exigiria dois ou três ciclos. E ainda vem com a AddWash, aquela portinha que já salvou muita peça esquecida. O único alerta: ela é um pouco mais alta que as concorrentes — mede direitinho o espaço antes de comprar.',
    pros: [
      '13kg de lavagem e 8kg de secagem — números que as outras lavadoras e secadoras do mercado simplesmente não alcançam',
      'Edredom de casal cabe tranquilo e ainda sobra espaço — testado na prática',
      'Ciclo contínuo de lavar e secar sem precisar transferir roupa',
      '16 programas inteligentes cobrem qualquer cenário que você imaginar',
      'Classe A de eficiência energética — não é porque é grande que é gastona',
    ],
    cons: [
      'Mais alta que a média (88cm) — se o seu armário é justo, meça antes de se apaixonar',
      'Só funciona em 220V — se a sua casa é 127V, infelizmente não rola',
    ],
    features: [
      'Capacidade monstra: 13kg na lavagem e 8kg na secagem',
      'Porta AddWash pra não passar raiva com peça esquecida',
      'Motor Digital Inverter durável e eficiente',
      'Tecnologia Ecobubble que limpa bem até em água fria',
      '16 programas inteligentes pra cada tipo de situação',
      'Controle remoto via Wi-Fi pelo app SmartThings',
      'Eficiência energética classe A',
      'Dimensões: 88cm altura, 60cm largura, 65cm profundidade',
    ],
    ideal: 'Família grande que não aguenta mais dividir a roupa da semana em três ciclos diferentes — cinco pessoas ou mais, casa com criança, edredom e toalha rolando solto todo fim de semana.',
    scoreBreakdown: {
      desempenho: 9.5,
      economia: 8.9,
      silencio: 8.8,
      recursos: 9.5,
      custoBeneficio: 8.7,
    },
  },
  {
    id: 'electrolux-lsp11-turbo',
    slug: 'electrolux-lsp11-turbo',
    rank: 4,
    name: 'Electrolux LSP11 Turbo',
    brand: 'Electrolux',
    badge: 'Custo-Benefício',
    badgeTone: 'value',
    image: '/images/products/lava-e-seca-electrolux-lsp11.webp',
    rating: 4.7,
    reviewsCount: 3421,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B084RVVF5S',
    priceFrom: 3999,
    headline: 'A máquina que não inventa moda: lava, seca, não trava e cabe no orçamento.',
    pitch:
      'Olha, tem eletrodoméstico que é igual carro popular: não tem teto solar nem banco de couro, mas te leva onde você precisa e não quebra. A Electrolux LSP11 é isso no mundo das lavadoras e secadoras. Sem Wi-Fi, sem IA, sem frufru — mas o Tira Manchas dela é honestíssimo. Já vi tirar barro de uniforme de futebol infantil e mancha de vinho tinto de toalha de mesa que eu já tinha dado como perdida. Comprei a minha numa Black Friday pagando bem menos que as Samsung equivalentes e, quase dois anos depois, segue firme. Pra quem quer um equipamento que faz o básico muito bem feito, é pedida certa.',
    pros: [
      'Preço mais camarada entre as de 11kg — e sem sentir que tá comprando coisa vagabunda',
      'O Tira Manchas com 4 níveis é real — funciona onde os genéricos só enganam',
      'Painel simples e direto, ótimo pra quem não quer aprender a mexer em mais um app',
      'Turbo Economia ajusta água e energia de verdade, não é só nome bonito no botão',
      'Assistência técnica da Electrolux cobre o Brasil inteiro sem drama',
    ],
    cons: [
      'Nada de controle por Wi-Fi ou app — ligou, programou e pronto',
      'Faz mais barulho que as Samsung e LG, especialmente na centrifugação',
    ],
    features: [
      '11kg de lavagem e 7kg de secagem — tamanho padrão pra famílias de médio porte',
      'Programa Tira Manchas com quatro intensidades diferentes',
      'Modo Turbo Economia que reduz o consumo de água e energia',
      '13 programas de lavagem pra diferentes necessidades',
      'Acabamento em aço inox que não enferruja com o tempo',
      'Sistema Jet Clean que mantém o cesto livre de resíduos',
      'Dimensões: 85cm altura, 60cm largura, 66cm profundidade',
    ],
    ideal: 'O comprador pé no chão — não quer app, não quer IA, quer uma máquina que lave e seque bem por anos sem dar dor de cabeça nem estourar o cartão de crédito.',
    scoreBreakdown: {
      desempenho: 9.0,
      economia: 9.4,
      silencio: 8.3,
      recursos: 8.2,
      custoBeneficio: 9.7,
    },
  },
  {
    id: 'samsung-ecobubble-digital-inverter',
    slug: 'samsung-ecobubble-digital-inverter',
    rank: 5,
    name: 'Samsung Ecobubble Digital Inverter',
    brand: 'Samsung',
    badge: 'Tecnologia Ecobubble',
    badgeTone: 'tech',
    image: '/images/products/samsung-lava-e-seca-digital-inverter-ecobubble.webp',
    rating: 4.8,
    reviewsCount: 2156,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0CB51NXF2',
    priceFrom: 4299,
    headline: 'A prova viva de que água fria limpa — e de quebra alivia a conta de luz no fim do mês.',
    pitch:
      'O que vende essa máquina é o tal do Ecobubble: o sistema mistura sabão, ar e água antes de jogar no cesto, criando uma espuma que penetra no tecido muito mais rápido que água pura. Na prática, lavei uma camisa social branca com mancha de suor em água fria e ela saiu mais limpa do que em outra máquina no ciclo quente. Se você lava roupa quase todo dia, a economia na conta de luz ao longo do ano é significativa. O motor Digital Inverter com 20 anos de garantia é o mesmo das irmãs mais caras, então em durabilidade ela não deve nada a ninguém.',
    pros: [
      'Ecobubble é o diferencial real — limpeza profunda em água fria, sem exagero de marketing',
      'Smart Check diagnostica falhas pelo celular antes de você precisar chamar técnico',
      '14 programas cobrem praticamente qualquer tipo de roupa ou sujeira',
      'Motor Digital Inverter com 20 anos de garantia — mesma segurança dos modelos top',
      'Preço mais acessível que a WD11M, mas com a mesma base tecnológica',
    ],
    cons: [
      'Visual mais careta que as outras Samsung — não chama atenção na lavanderia',
      'Toalhas e roupas grossas saem da secagem com leve umidade residual',
    ],
    features: [
      'Sistema Ecobubble que gera espuma concentrada antes de molhar a roupa',
      '11kg de lavagem e 7kg de secagem',
      'Motor Digital Inverter com garantia estendida de 20 anos',
      'Smart Check que lê códigos de erro via smartphone',
      '14 programas de lavagem especializados',
      'Dispensador automático de sabão líquido',
      'Dimensões: 85cm altura, 60cm largura, 65cm profundidade',
    ],
    ideal: 'Quem lava roupa com frequência e sente no bolso o peso da conta de luz — gente prática que quer um equipamento durável sem pagar o preço do modelo topo de linha.',
    scoreBreakdown: {
      desempenho: 9.3,
      economia: 9.6,
      silencio: 9.0,
      recursos: 9.2,
      custoBeneficio: 9.1,
    },
  },
  {
    id: 'samsung-wd11a-ecobubble',
    slug: 'samsung-wd11a-ecobubble',
    rank: 6,
    name: 'Samsung WD11A Ecobubble',
    brand: 'Samsung',
    badge: 'Alternativa Samsung',
    badgeTone: 'neutral',
    image: '/images/products/lava-e-seca-samsung-wd11a.webp',
    rating: 4.7,
    reviewsCount: 1789,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0CB6TK5J8',
    priceFrom: 4199,
    headline: 'A prima moderninha da Ecobubble clássica — mesma alma, visual renovado e um dispensador mais esperto.',
    pitch:
      'Vamos ser diretos: a WD11A é essencialmente a mesma máquina Ecobubble que todo mundo conhece, só que com uma cara nova e alguns ajustes pontuais que fazem diferença no dia a dia. O dispensador automático foi recalibrado e agora desperdiça menos sabão — parece detalhe, mas ao longo de um ano é uma economia que vale o upgrade. O painel está mais limpo e intuitivo, então até sua avó vai saber programar sem pedir ajuda. Se você namora a Ecobubble mas quer o modelo com visual mais atualizado, é essa aqui. Se a tradicional estiver mais barata numa promoção, vá nela sem medo também — a diferença não justifica pagar muito a mais.',
    pros: [
      'Mesmo coração da Ecobubble que o Brasil já aprovou — mecânica confiável',
      'Dispensador de sabão mais preciso, menos desperdício no longo prazo',
      '14 programas com interface mais amigável que a antecessora',
      'Smart Check via Wi-Fi continua funcionando bem',
      'Custo costuma despencar em Black Friday — ótima hora pra pegar',
    ],
    cons: [
      'Muda muito pouco em relação à Ecobubble tradicional — não espere revolução',
      'O cabo de força é curto — se a tomada for longe, já prepara a extensão',
    ],
    features: [
      'Tecnologia Ecobubble de limpeza em água fria',
      '11kg de lavagem e 7kg de secagem',
      'Motor Digital Inverter silencioso e durável',
      '14 programas de lavagem cobrindo todos os tipos de uso',
      'Dispensador automático de sabão aprimorado',
      'Diagnóstico Smart Check pelo aplicativo SmartThings',
    ],
    ideal: 'Quem já decidiu pela Ecobubble mas quer o design mais moderno — ou quem encontrou a tradicional esgotada e precisa de uma alternativa quase idêntica.',
    scoreBreakdown: {
      desempenho: 9.2,
      economia: 9.4,
      silencio: 8.9,
      recursos: 9.0,
      custoBeneficio: 9.0,
    },
  },
  {
    id: 'midea-mf200d-storm-wash',
    slug: 'midea-mf200d-storm-wash',
    rank: 7,
    name: 'Midea MF200D Storm Wash',
    brand: 'Midea',
    badge: 'Preço Acessível',
    badgeTone: 'value',
    image: '/images/products/lava-e-seca-midea-mf200d105wb.webp',
    rating: 4.5,
    reviewsCount: 987,
    capacityWash: 10.1,
    capacityDry: 6,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0C6B5WHS1',
    priceFrom: 2899,
    headline: 'A porta de entrada mais honesta do segmento: não finge ser premium, mas entrega o essencial.',
    pitch:
      'A Midea MF200D foi a primeira lavadora e secadora da minha cunhada — ela mora num apartamento pequeno, tinha orçamento apertado e zero experiência com máquinas desse tipo. Dois anos depois, o bichinho segue firme. O acabamento não é luxo, mas a função Steam Care manda bem em roupa de bebê (elimina ácaros e bactérias que nenhum sabão tira sozinho), e o ciclo rápido de 15 minutos é utilidade pública na correria. A secagem é o calcanhar de aquiles — em carga cheia, precisa de uma segunda passada, especialmente em jeans e toalhas. Mas pelo preço, tá mais do que justo. É o tipo de eletrodoméstico que não te impressiona na especificação, mas te conquista no dia a dia.',
    pros: [
      'Preço que não faz você parcelar em 24 vezes com lágrimas nos olhos',
      'Steam Care é aliado de quem tem bebê em casa — elimina ácaros que sobrevivem à lavagem normal',
      'Ciclo rápido de 15 minutos que realmente funciona pra roupas do dia a dia',
      '15 programas no total — variedade surpreendente pra faixa de preço',
      'Motor Inverter — a Midea não economizou onde importa',
    ],
    cons: [
      'Secagem em carga máxima é incompleta — se prepara pra segunda rodada',
      'Assistência técnica escassa fora das capitais — antes de comprar, confirma se tem na sua região',
    ],
    features: [
      '10,1kg de lavagem e 6kg de secagem — ideal pra casais e famílias pequenas',
      'Tecnologia Storm Wash que aumenta a eficiência da lavagem',
      'Função vapor Steam Care pra eliminar alérgenos',
      'Ciclo expresso de 15 minutos pra emergências',
      '15 programas de lavagem no total',
      'Motor Inverter com boa durabilidade',
    ],
    ideal: 'O comprador de primeira viagem — nunca teve uma lavadora e secadora, quer gastar pouco e precisa de uma máquina honesta pra um apartamento compacto ou família de até três pessoas.',
    scoreBreakdown: {
      desempenho: 8.4,
      economia: 8.8,
      silencio: 8.1,
      recursos: 8.5,
      custoBeneficio: 9.5,
    },
  },
  {
    id: 'hisense-wd3s11-smart',
    slug: 'hisense-wd3s11-smart',
    rank: 8,
    name: 'Hisense WD3S11 Smart',
    brand: 'Hisense',
    badge: 'Controle Smart',
    badgeTone: 'tech',
    image: '/images/products/lava-e-seca-hisense-wd3s11.webp',
    rating: 4.4,
    reviewsCount: 756,
    capacityWash: 11,
    capacityDry: 7,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B08DMTGN38',
    priceFrom: 3499,
    headline: 'A carta na manga de quem quer vapor, Wi-Fi e 16 programas — pagando bem menos que as gigantes.',
    pitch:
      'A Hisense é aquela marca que muita gente torce o nariz até conhecer de perto — e no caso dessa lavadora e secadora, o preconceito passa rápido. A WD3S11 entrega vapor de verdade, conectividade via app e 16 programas bem calibrados. Tecnicamente, joga no mesmo time de Samsung e LG, mas com uma etiqueta de preço bem mais camarada. Rodei um ciclo com vapor em roupa de cama e o resultado foi honesto — cheiro de limpo e menos amassados. O aplicativo não é tão polido quanto o SmartThings, e o suporte técnico ainda está engatinhando em cidades menores, mas se você mora em capital e quer o máximo de recursos pelo menor preço, esse modelo merece sua atenção.',
    pros: [
      'Relação recursos vs. preço é a melhor do ranking — vapor, Wi-Fi e 16 programas por valor de entrada',
      '16 programas de lavagem bem distribuídos — cobre tudo que você precisa',
      'Função vapor integrada que funciona pra valer, não é só marketing',
      'Controle remoto por smartphone — liga, pausa e acompanha o ciclo do sofá',
      'Classe A de eficiência energética — certificação que muitas marcas conhecidas não entregam nessa faixa',
    ],
    cons: [
      'App ConnectLife tem umas travadas eventuais — nada grave, mas irrita quando acontece',
      'Marca ainda pouco conhecida no interior — se você mora longe de capital, cheque a assistência antes',
    ],
    features: [
      '11kg de lavagem e 7kg de secagem',
      'Função vapor pra desamassar e higienizar',
      'Conexão Wi-Fi com app ConnectLife',
      '16 programas de lavagem especializados',
      'Motor Inverter eficiente',
      'Classificação energética A',
    ],
    ideal: 'O caçador de custo-benefício — quer Wi-Fi, vapor e programas variados, mas não está disposto a pagar o pedágio das marcas premium. Morador de capital ou região metropolitana.',
    scoreBreakdown: {
      desempenho: 8.7,
      economia: 9.0,
      silencio: 8.5,
      recursos: 9.1,
      custoBeneficio: 9.2,
    },
  },
  {
    id: 'brastemp-bnq10-inverter',
    slug: 'brastemp-bnq10-inverter',
    rank: 9,
    name: 'Brastemp BNQ10AB Inverter',
    brand: 'Brastemp',
    badge: 'Marca Nacional',
    badgeTone: 'neutral',
    image: '/images/products/lava-e-seca-brastemp-bnc10ab.webp',
    rating: 4.4,
    reviewsCount: 1234,
    capacityWash: 10,
    capacityDry: 6.5,
    energyClass: 'A',
    voltage: '127V / 220V',
    asin: 'B0FW15RTK6',
    priceFrom: 3799,
    headline: 'Não tem Wi-Fi, não tem vapor — mas tem a assistência técnica que chega até na sua cidade do interior.',
    pitch:
      'Minha mãe é do time "Brastemp ou nada", e eu já desisti de convencê-la do contrário — até porque ela tem razão em um ponto fundamental. Quando uma máquina quebra no interior de Minas ou no litoral de Santa Catarina, o técnico da Brastemp aparece. O da marca importada, nem sempre. A BNQ10AB é honesta: 10kg de lavagem, 6,5kg de secagem, Tira Manchas que funciona e Turbo Economia que reduz o consumo sem milagre. Não vai te impressionar com design futurista, mas não vai te deixar na mão três meses depois da compra. É aquela escolha que sua mãe faria — e olha, às vezes a mãe tem razão.',
    pros: [
      'Rede de assistência técnica presente em praticamente qualquer cidade brasileira',
      'Função Tira Manchas eficiente — tira o que promete sem precisar de pré-lavagem',
      'Turbo Economia que faz diferença real no consumo de água e energia',
      'Motor Inverter durável — condizente com a fama de tanque de guerra da Brastemp',
      'Peças de reposição fáceis e baratas — não vai ficar dois meses esperando importar componente',
    ],
    cons: [
      'Capacidade de 10kg é a menor do ranking — se a família é grande, vai passar aperto',
      'Painel sem conectividade — é no botão físico mesmo, old school total',
    ],
    features: [
      '10kg de lavagem e 6,5kg de secagem',
      'Motor Inverter com boa eficiência e durabilidade',
      'Programa Tira Manchas dedicado',
      'Função Turbo Economia',
      '12 programas de lavagem',
    ],
    ideal: 'Quem mora fora dos grandes centros e valoriza a tranquilidade de saber que, se der problema, o conserto é rápido e sem drama — ou quem simplesmente confia na Brastemp por tradição familiar.',
    scoreBreakdown: {
      desempenho: 8.6,
      economia: 8.9,
      silencio: 8.4,
      recursos: 8.1,
      custoBeneficio: 9.0,
    },
  },
];

export function productByRank(rank) {
  return products.find((p) => p.rank === rank);
}

export function productBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function averageRating() {
  const sum = products.reduce((acc, p) => acc + p.rating, 0);
  return +(sum / products.length).toFixed(2);
}

export function totalReviews() {
  return products.reduce((acc, p) => acc + p.reviewsCount, 0);
}
